### ISSUE TITLE
Should I need to specify credentials in project.clj to use this?

### ISSUE THREAD

**Issue by timvisher** [robertluo/lein-aws-maven#1]
I could've sworn I had this working but now it doesn't seem to be anymore. I have `s3://` repositories in my project.clj with no credentials specified. My understanding then is that `lein-aws-maven` should pull my credentials from the environment given that the s3wagon provided by `aws-maven` does that by default.

Is there something I'm missing there?

**Comment by robertluo** [comment]
I updated the README.md to show how to use environment variables to set the credentials.

**Comment by timvisher** [comment]
@robertluo What if we _want_ to sign releases? And what if we wanted to use `EC2 IAM Roles` for the creds rather than env vars?

**Comment by robertluo** [comment]
The plugin is just a workaround for simplest scenario, so these features are out of the scope.

**Comment by memory** [comment]
@timvisher this is actually an issue w/ leiningen itself upstream: https://github.com/technomancy/leiningen/pull/1990

**Comment by memory** [comment]
This is now fixed in technomancy/leiningen master.  Set `:no-auth true` and all will be well.
